version: '3.4'

services:
  rstudio:
    build: "."
    image: mobilecommercelab/rqda-rstudio-sshd
    environment:
      - ROOT_PASSWORD
    ports:
      - "${LISTEN_SSHD}:22"
    volumes:
      - "./rstudio:/root/rstudio"
